### ISSUE TITLE
[Feature Request] Add the option to use a specific package instead of scanning all packages

### ISSUE THREAD

**Issue by BehindTheMath** [papandreou/npm-bisect#2]
Sometimes I know that a specific dependency caused the regression; I just don't know which version. If there would be an option to just focus on that package, it would save time.

**Comment by BehindTheMath** [comment]
Another possibility would be to add a whitelist option, as the opposite of `--ignore`.

**Comment by papandreou** [comment]
Great idea, PR welcome :). Should we call it `--only` or something?

I'm sorry there's no test suite, this was just a quick weekend hack. Will add one soon.

**Comment by BehindTheMath** [comment]
If both `--ignore` and `--only` are used, which takes precedence?

**Comment by papandreou** [comment]
Maybe that combination should just error out? Doesn’t really make sense to have both, unless we introduce a way to `only`/`ignore` specific package *versions* as well? Eg.:

```
npm-bisect --only lodash --ignore lodash@^1.4.6
```

**Comment by papandreou** [comment]
Implemented `--only` and the version range ability in 1.2.0 :)
